theme: 
  - osuny
  - osuny-plugin-pagedjs
_merge: deep
params:
  debug:
    active: true
    productionUrl: https://example.osuny.org
  logo:
    header:
      default: "/assets/images/logo-osuny.svg"
      darkmode: "/assets/images/logo-osuny-white.svg"
    footer:
      default: "/assets/images/logo-osuny.svg"
      darkmode: "/assets/images/logo-osuny-white.svg"
  search:
    active: true
    positions:
      - primary
      - footer
  events:
    index:
      options:
        place: true
  organizations:
    single:
      backlinks: true
  pages:
    index:
      options:
        categories: true
  persons:
    index: 
      layout: list # grid | list
    single:
      backlinks: true
